### ISSUE TITLE
issue with merge and switching older concepts

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#126]
From Liz:

I was logged in as Alice and was trying to do a merge where NANOS3 wt Allele C104840 (primitive) was the surviving partner and NBL1 wt Allele C53089 (defined) was the retiring partner. I never got a warning that the retiring partner was the older concept. Additionally, I could hit the Merge button and the merge occurred but I could not Save (commit) the merge. I had to cancel. Below this message I have included the console output after hitting the Save button.

I tried another merge where IL-2R Alpha-Positive Neoplastic Cells Present C71599 (primitive) was the surviving partner and CD25-Positive Neoplastic Cells Present C70850 (primitive) was the retiring partner. I never got a warning that the retiring partner was the older concept. Again, I could hit the Merge button and the merge occurred but I could not Save (commit) the merge. I had to cancel. A similar message was in the console.

Not knowing what was wrong, I logged out and logged back in and tried the second merge again. Again, the Merge button worked but the Save did not. So either there is something that is changed with Alice's permissions since the previous snapshot or there is something wrong in the merge approval process.

Here is the console output after hitting the Save button for the first merge attempt above.
````
Uncaught Exception in thread 'AWT-EventQueue-0'
java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Unknown Source) ~[na:1.8.0_102]
        at gov.nih.nci.ui.NCIEditTab.doCommit(NCIEditTab.java:998) ~[na:na]
        at gov.nih.nci.ui.NCIEditTab.commitChanges(NCIEditTab.java:964) ~[na:na]

        at gov.nih.nci.ui.ComplexEditPanel$1.actionPerformed(ComplexEditPanel.java:169) ~[na:na]
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Component.processMouseEvent(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.JComponent.processMouseEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Component.processEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Container.processEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Component.dispatchEventImpl(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Container.dispatchEventImpl(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Component.dispatchEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Container.dispatchEventImpl(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Window.dispatchEventImpl(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Component.dispatchEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source) ~[na:1.8.0_102]

        at java.awt.EventQueue.access$500(Unknown Source) ~[na:1.8.0_102]
        at java.awt.EventQueue$3.run(Unknown Source) ~[na:1.8.0_102]
        at java.awt.EventQueue$3.run(Unknown Source) ~[na:1.8.0_102]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_102]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[na:1.8.0_102]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[na:1.8.0_102]
        at java.awt.EventQueue$4.run(Unknown Source) ~[na:1.8.0_102]
        at java.awt.EventQueue$4.run(Unknown Source) ~[na:1.8.0_102]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_102]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[na:1.8.0_102]
        at java.awt.EventQueue.dispatchEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [na:1.8.0_102]
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [na:1.8.0_102]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [na:1.8.0_102]
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [na:1.8.0_102]
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [na:1.8.0_102]
        at java.awt.EventDispatchThread.run(Unknown Source) [na:1.8.0_102]
Checking for updates
Updating index with 7 change(s)
Uncaught Exception in thread 'AWT-EventQueue-0'
java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Unknown Source) ~[na:1.8.0_102]
        at gov.nih.nci.ui.NCIEditTab.doCommit(NCIEditTab.java:998) ~[na:na]
        at gov.nih.nci.ui.NCIEditTab.commitChanges(NCIEditTab.java:964) ~[na:na]

        at gov.nih.nci.ui.ComplexEditPanel$1.actionPerformed(ComplexEditPanel.java:169) ~[na:na]
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Component.processMouseEvent(Unknown Source) ~[na:1.8.0_102]
        at javax.swing.JComponent.processMouseEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Component.processEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Container.processEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Component.dispatchEventImpl(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Container.dispatchEventImpl(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Component.dispatchEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Container.dispatchEventImpl(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Window.dispatchEventImpl(Unknown Source) ~[na:1.8.0_102]
        at java.awt.Component.dispatchEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source) ~[na:1.8.0_102]

        at java.awt.EventQueue.access$500(Unknown Source) ~[na:1.8.0_102]
        at java.awt.EventQueue$3.run(Unknown Source) ~[na:1.8.0_102]
        at java.awt.EventQueue$3.run(Unknown Source) ~[na:1.8.0_102]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_102]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[na:1.8.0_102]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[na:1.8.0_102]
        at java.awt.EventQueue$4.run(Unknown Source) ~[na:1.8.0_102]
        at java.awt.EventQueue$4.run(Unknown Source) ~[na:1.8.0_102]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_102]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source) ~[na:1.8.0_102]
        at java.awt.EventQueue.dispatchEvent(Unknown Source) ~[na:1.8.0_102]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [na:1.8.0_102]
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [na:1.8.0_102]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [na:1.8.0_102]
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [na:1.8.0_102]
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [na:1.8.0_102]
        at java.awt.EventDispatchThread.run(Unknown Source) [na:1.8.0_102]
Checking for updates
````

**Comment by bdionne** [comment]
fixed in [nci-0.111](https://github.com/NCIEVS/nci-protege5/releases)

**Comment by rmehri** [comment]
The same issue exists in tag 116.

I logged into the local server as Alice (Workflow Manager) and tried to do a merge where Mouse Discharge (C26416) was the surviving partner and concept "C83485" was the retired partner. When I clicked Merge button the same following error occurred.   Please attached log file for more details. 


[Uploading Merged_Errror_Log File.txt…]()
Uncaught Exception in thread 'AWT-EventQueue-0'
java.lang.NumberFormatException: For input string: "etired_Concept_Current_Year"

        at java.lang.NumberFormatException.forInputString(NumberFormatException.
java:65) ~[na:1.8.0_101]
        at java.lang.Integer.parseInt(Integer.java:580) ~[na:1.8.0_101]
        at java.lang.Integer.parseInt(Integer.java:615) ~[na:1.8.0_101]
        at org.protege.editor.owl.client.LocalHttpClient.codeIsLessThan(LocalHtt
pClient.java:755) ~[na:na]
        at gov.nih.nci.ui.NCIEditTab.switchMergeSourceTarget(NCIEditTab.java:596
) ~[na:na]
        at gov.nih.nci.ui.NCIEditTab.merge(NCIEditTab.java:524) ~[na:na]
        at gov.nih.nci.ui.ComplexEditPanel$1.actionPerformed(ComplexEditPanel.ja
va:172) ~[na:na]
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:20
22) ~[na:1.8.0_101]
        at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.jav
a:2348) ~[na:1.8.0_101]
        at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel
.java:402) ~[na:1.8.0_101]
        at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259
) ~[na:1.8.0_101]
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonL
istener.java:252) ~[na:1.8.0_101]
        at java.awt.Component.processMouseEvent(Component.java:6533) ~[na:1.8.0_
101]
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) ~[na:1
.8.0_101]
        at java.awt.Component.processEvent(Component.java:6298) ~[na:1.8.0_101]
        at java.awt.Container.processEvent(Container.java:2236) ~[na:1.8.0_101]
        at java.awt.Component.dispatchEventImpl(Component.java:4889) ~[na:1.8.0_
101]
        at java.awt.Container.dispatchEventImpl(Container.java:2294) ~[na:1.8.0_
101]
        at java.awt.Component.dispatchEvent(Component.java:4711) ~[na:1.8.0_101]

        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888
) ~[na:1.8.0_101]
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
 ~[na:1.8.0_101]
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466) ~[n
a:1.8.0_101]
        at java.awt.Container.dispatchEventImpl(Container.java:2280) ~[na:1.8.0_
101]
        at java.awt.Window.dispatchEventImpl(Window.java:2746) ~[na:1.8.0_101]
        at java.awt.Component.dispatchEvent(Component.java:4711) ~[na:1.8.0_101]

        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) ~[na:1.8.0
_101]
        at java.awt.EventQueue.access$500(EventQueue.java:97) ~[na:1.8.0_101]
        at java.awt.EventQueue$3.run(EventQueue.java:709) ~[na:1.8.0_101]
        at java.awt.EventQueue$3.run(EventQueue.java:703) ~[na:1.8.0_101]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0
_101]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionP
rivilege(ProtectionDomain.java:76) ~[na:1.8.0_101]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionP
rivilege(ProtectionDomain.java:86) ~[na:1.8.0_101]
        at java.awt.EventQueue$4.run(EventQueue.java:731) ~[na:1.8.0_101]
        at java.awt.EventQueue$4.run(EventQueue.java:729) ~[na:1.8.0_101]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0
_101]
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionP
rivilege(ProtectionDomain.java:76) ~[na:1.8.0_101]
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) ~[na:1.8.0_101
]
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThre
ad.java:201) [na:1.8.0_101]
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.
java:116) [na:1.8.0_101]
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThre
ad.java:105) [na:1.8.0_101]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 [na:1.8.0_101]
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
[na:1.8.0_101]
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [na:1.8
.0_101]


[Merged_Error_Log File.txt](https://github.com/NCIEVS/nci-protege5/files/692718/Merged_Error_Log.File.txt)

**Comment by bdionne** [comment]
From the log it appears you are trying to merge `Retired_Concept_Current_Year`

**Comment by rmehri** [comment]
Hi, 
I have retested this issue using Retired Concept (C83485) and surviving Concept  "Mouse Discharge" (C26416).  The same issue  still exists.  Please see attached zip file for screen shot and log file for more details.
Thanks,
Reza 


[Merge_Issue_126.zip](https://github.com/NCIEVS/nci-protege5/files/711386/Merge_Issue_126.zip)

**Comment by rmehri** [comment]
Based on your feedback, this ticket is closed and will open a new ticket for the reported java error to be prevented.

Thanks, 
Reza

**Comment by rmehri** [comment]
The following issue has been created related to the exception error:
https://github.com/NCIEVS/nci-protege5/issues/183

Thanks,
Reza

**Comment by bdionne** [comment]
@rmehri - this is the same error, you are merging a class that doesn't have a code in the `IRI` for the class. I'm not sure what we plan to do about these yeat

[Merge_Error.zip](https://github.com/NCIEVS/nci-protege5/files/724735/Merge_Error.zip)

**Comment by bdionne** [comment]
Always use the code property for merge comparisons, instead of the IRI. This will take care of legacy classes

**Comment by rmehri** [comment]
This issue will be retested in next build.  
Thanks,
Reza

**Comment by bdionne** [comment]
[fixed](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.118)

**Comment by rmehri** [comment]
This fix has been retested using tag-118, edittab-03.3, No java error was received. But verified the warning message that the retiring partner was the older concept.  Please see attached screen shot for more detail. 

![merge_warning msg](https://cloud.githubusercontent.com/assets/8367102/22439531/00cd1d2e-e6fe-11e6-9adf-266ea5eafabd.png)
Thanks,
Reza
