### ISSUE TITLE
check for punctuation only for preferred name, not definitions

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#201]

**Comment by bdionne** [comment]
[fixed](https://github.com/NCIEVS/nci-protege5/releases/tag/nci-0.124)

**Comment by rmehri** [comment]
Hi Bob, 
 Please elaborate about what punctuation only for preferred name. Is this issue somehow related to this ticket https://github.com/NCIEVS/nci-protege5/issues/202? 

Thanks,
Reza

**Comment by bdionne** [comment]
From the subject line above:

"check for punctuation only for preferred name, not definitions"

and from #202, the last comment: 

"The punctuation restrictions only apply to preferred_name"

What this means, and you can verify using `nci-0.123` is that the punctuation rules were being applied to other properties such as `DEFINITION` and `ALT_DEFINITION`. Ticket #202 refers to the punctuation rule itself. This ticket refers to the fact that the rule is only applied to `preferred_name`

**Comment by rmehri** [comment]
Hi Bob, 
Thanks for your comment.  I am still not clear on what punctuation restrictions can/cannot apply to preferred_name.  According to the following link, please specify.

Properties cannot include the characters :,!,? or @ (except for DEFINITION which allows ! and ?)
https://github.com/NCIEVS/nci-protege5/wiki/editing-rules-enforced-by-nci-protege

Thanks,
Reza

**Comment by NCIEVS** [comment]
out of the set above, the only new ones that are allowed in preferred_name are the colon ":" and the at "@".

**Comment by bdionne** [comment]
@rmehri - to clarify @NCIEVS comment further and to answer you last question in #202:

The original requirement from the WIKI page was to *prevent* the characters `:, !, ?, and @` from occurring in the `preferred_name`. As I noted, the WIKI page was a incorrect and the modelers are currently in the process of updating it. 

Two problems were identified:

1. #202 - "Allow : in preferred name" - Note that the `preferred_name`, the `FULL_SYN` that has source `NCI` and term group `PT`, and the `rdfs:label` always have the same value so this rule will hold for them as well. It was identified that we also want to all `@`, so as @NCIEVS  comments above int he `preferred_name` we allow `: and @` but continue to *prevent* `! and ?`

2. #201 - "check for punctuation only for preferred name, not definitions" - This rule for `preferred_name` does not apply to `DEFINITION` and `ALT_DEF`, which is what this ticket is for.

I hope this helps

**Comment by rmehri** [comment]
Hi Bob,
Thanks for your feedback! 
Reza

**Comment by rmehri** [comment]
This fix has been has retested. Please see attached screen shots 

![preferred_name-1](https://cloud.githubusercontent.com/assets/8367102/23872636/6e351510-0805-11e7-8e43-a2bdd31ddb4a.png)

Thanks,
Reza
