### ISSUE TITLE
Disjointness pop-up fires when superclasses are not disjoint

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#445]
This is in 3.3.0.  This edit check also looks for redundant parents, but one occasion today fired the "disjointness" notice when the "redundant parents" was more appropriate.  @ncievs and others will need to flesh out this ticket with test case scenarios.

**Comment by bdionne** [comment]
This is fixed in tag [3.3.1-qa1](https://github.com/NCIEVS/protege/commits/3.3.1-qa1)

**Comment by bdionne** [comment]
fixed in 3.4.0-dev1 tag

**Comment by singhik** [comment]
@NCIEVS : Hi, Unable to reproduce this scenario with 'Disjointed Concepts' being Parents for a Concept and Save is allowed successfully with out any pop up or Error warnings .  Also, tried Redundant Parents for a Concept and Save, with out any pop up or warning .

Please provide an example ,if possible .

**Comment by NCIEVS** [comment]
Hi @singhik , I think it's because the check is now part of the Curator plugin, but it wasn't included in the dev2 distribution.  @bdionne should be able to confirm that Curator needs to be present, and maybe also @safrant can talk to the distribution (maybe the plugin wasn't meant to be in dev2?).

**Comment by bdionne** [comment]
@NCIEVS @singhik - right, this ticket was because the functionality, checking for disjointness, was not working correctly in the last release. We took it out of protege, so you should not see the popup at all, correctly or incorrectly. 

The functionality is moved to EditTab and will appear when that plugin is published. So you can mark this passed and close it

**Comment by NCIEVS** [comment]
@singhik , oh, and for test cases:

1 for disjointness check, take CAGE1 Gene (code C139924) and add Gene Product (code C26548) as a second parent.
2 for redundant parent check, take CAGE1 Gene above, and add Gene (code C16612) as a second parent.

**Comment by NCIEVS** [comment]
@bdionne , this might be part of Curator proper, but I thought it should have been working with Pellet.  In the test case 2 above for redundant parents, I was expecting to see a "suggestion" to remove the redundant Gene parent in the inferred axioms section of the classification panel, but I'm not seeing it.  Does the removal suggestion only appear in Curator?  Here's a screenshot:

![image](https://user-images.githubusercontent.com/7783321/87823255-f4475880-c840-11ea-8c9c-37a410788318.png)

**Comment by bdionne** [comment]
@NCIEVS not sure, I never tried it with Pellet. I know we added code to protege to check redundancy when it the classifier finds a new parent, but I don't think we ever looked at this case which is just the user adding a redundancy. I think this is the common error Nick at. al. wanted fixed.

In the new classifier it's caught at edit time

**Comment by singhik** [comment]
@bdionne : Hi ,  Not getting the pop-warning which gives user the 'Accept' or 'Reject' options for 'Disjointness', 'Redundancy' or ' Language Constructs' ??  Tag is 3.4.0-qa1 . Concept gets saved successfully, without the Expected Warning prompt pop-up ?

![image](https://user-images.githubusercontent.com/36314371/88709801-a86b9d80-d0e3-11ea-88d4-da2961ab6c97.png)

![image](https://user-images.githubusercontent.com/36314371/88709839-b6212300-d0e3-11ea-9af9-29870b0e09ec.png)

**Comment by singhik** [comment]
@bdionne : Hi, Still don't see the Warning Message Pop-up For Disjointness and Redundancy ?

![image](https://user-images.githubusercontent.com/36314371/88724507-9fd19200-d0f8-11ea-8ab1-003a8069f58e.png)

![image](https://user-images.githubusercontent.com/36314371/88724525-a7913680-d0f8-11ea-8eb6-deb85a5fdbae.png)


Plug-Ins ::

![image](https://user-images.githubusercontent.com/36314371/88724559-b972d980-d0f8-11ea-8273-bc197b9b8314.png)

**Comment by bdionne** [comment]
are your settings configured to enable the checks?

**Comment by singhik** [comment]
@bdionne : Hi, Looks like below , Yes running on 3.4.0-qa1 client, URL for client is 'https://cbiit-download.nci.nih.gov/evs/Protege/Protege-5-Snapshots/nci-protege-V3.4.0-qa1.zip'


![image](https://user-images.githubusercontent.com/36314371/88726027-fb9d1a80-d0fa-11ea-85e9-24c4cf562eed.png)


![image](https://user-images.githubusercontent.com/36314371/88726039-00fa6500-d0fb-11ea-8b53-f925dc50b4f7.png)

**Comment by bdionne** [comment]
not sure what this is, I'll try your build locally. Check your plugins folder, maybe the 1.1.3 version wasn't replaced and it's running both

**Comment by bdionne** [comment]
your build works fine here. Are the parents you're adding declared disjoint?

<img width="1008" alt="Screen Shot 2020-07-28 at 6 00 55 PM" src="https://user-images.githubusercontent.com/31741/88726854-76b30080-d0fc-11ea-8eb8-0676c8c5fb03.png">

**Comment by singhik** [comment]
@bdionne : Hi, Yes, the plugin folder did not overwrite the old one, i deleted the old one, restarted Protege, configuration looks like below, able to see the Pop Up for Disjointness now, testing Redundancy and other workflow now

**Comment by bdionne** [comment]
@singhik I also notice you have the plugin loaded, is it selected in the reasoner menu or is curator?

**Comment by singhik** [comment]
@bdionne : Hi,  'Preferences->Reasoner->Curator' , per below ::

![image](https://user-images.githubusercontent.com/36314371/88727334-6fd8bd80-d0fd-11ea-9e0d-d757fa087b42.png)

**Comment by bdionne** [comment]
ah great, that's also on our todo list, if I recall that's a windoze issue

**Comment by singhik** [comment]
@bdionne : Hi ,   

Issue> For Redundancy, DIsjoint & Language constructs, the Warning Pop-up, appears Twice, i.e. after clicking 'Ok' on the first Prompt, the second Warning also appears (Duplication of Warning Pop-up Messages) .

@NCIEVS : Hi, 

Question> For Redundant Parents, post classification completion, the 'Inference Results' Panel ,does not show any Messages or Warnings, like it shows for Disjoint & Language constructs, is this as Expected ?

**Comment by bdionne** [comment]
> Issue> For Redundancy, DIsjoint & Language constructs, the Warning Pop-up, appears Twice, i.e. after clicking 'Ok' on the first Prompt, the second Warning also appears (Duplication of Warning Pop-up Messages) .

Yes, it actually worse if you do multiple edits that create warnings. It turns out it's conflicting with the `SessionRecorder` of the history. I have a fix but it will require another build I think.

**Comment by singhik** [comment]
@bdionne : Hi, Defect, 'Inference Results' Panel displays unsupported constructs and disjoint parent info as expected, but when the File->Preferences->Curator  settings are changed (f.e. from limit explanations to show all explanations), 'Inference Results' panel refreshes and all the warning disappears :: 


![image](https://user-images.githubusercontent.com/36314371/89340864-65bf3d80-d66e-11ea-9ba1-dfbce12dd3f6.png)

Changing any option under Preferences->Curator (f.e. from Limit Explanations to Show All Explanations)  :: 

![image](https://user-images.githubusercontent.com/36314371/89341084-c51d4d80-d66e-11ea-9c65-4fb1c6f92c0b.png)


'Inference Results' Panel ,unsupported constructs and dijoint parent info vanishes :: 

![image](https://user-images.githubusercontent.com/36314371/89341242-001f8100-d66f-11ea-91f1-dc2c665e0e58.png)


NCI Edit ,Still has those unsupported constructs and disjoint parent :: 

![image](https://user-images.githubusercontent.com/36314371/89341308-19283200-d66f-11ea-96ce-d41e5d19dd5f.png)

![image](https://user-images.githubusercontent.com/36314371/89341332-20e7d680-d66f-11ea-86c1-e9acc37c5cee.png)

**Comment by bdionne** [comment]
@singhik This is not a defect, this is how it always works. When you set any of the preferences that classification state is reset. If you ran the classifier again those results would come back.

Also, the explanations are not supported in this first release. Maybe we should disable the preference completely but I left it there for now along with some default behavior if the user asks for one.

**Comment by singhik** [comment]
Disjointness pop-up Warning message with 'OK' & 'Cancel' buttons has been tested successfully on 3.4.0-qa2 Build client, Hence closing this ticket
