### ISSUE TITLE
Property values that contain logical keywords don't render correctly

### ISSUE THREAD

**Issue by bdionne** [NCIEVS/nci-protege5#7]
Seems to be a protege [issue](https://github.com/protegeproject/protege/issues/522)

**Comment by NCIEVS** [comment]
Was fixed upstream; seems we picked up the fix already.  Will label bug for v1 release and ready for QA.  

Another issue may have been created related to wraparound but will consult before creating a new ticket.

**Comment by rmehri** [comment]
Can you please clarify the reproducible or/fix steps so I can validate the fix? 

Thanks,
Reza

**Comment by bdionne** [comment]
If you click the link [above](https://github.com/protegeproject/protege/issues/522), notice in the screen shot that the words `and` and `or` appear colored in blue. The bug, is that protege is rendering text incorrectly. It's treating  that text as if it were a logical definition and coloring the logical symbols.

**Comment by rmehri** [comment]
Based on screen shot "above", the Classes tab is not available using any current user roles. Therefore, this ticket will remain open for further validation.  
Thanks,
Reza

**Comment by bdionne** [comment]
@rmehri -- correct, we haven't decided yet whether to expose that tab, however you can see the same `classes` tab within the `entities` tab, which a workflow manager has permissions for.

Also, the problem still persists and I've re-opened in protege:

<img width="1021" alt="screen shot 2016-12-16 at 12 29 37 pm" src="https://cloud.githubusercontent.com/assets/31741/21272200/3d7fd616-c38c-11e6-8a73-eb1650c60da8.png">

**Comment by bdionne** [comment]
I retract that, it actually is fixed, the rendering preferences just needs to be set up to not highlight keywords

<img width="1022" alt="screen shot 2016-12-16 at 1 07 35 pm" src="https://cloud.githubusercontent.com/assets/31741/21273341/20b9a6c4-c391-11e6-9de6-08bdc8a480e7.png">

**Comment by rmehri** [comment]
The fix for this issue has been retested and verified in tag 116.
Thanks,
Reza

![untitled](https://cloud.githubusercontent.com/assets/8367102/21786574/78450410-d692-11e6-994f-14c648c21cf5.png)
