### ISSUE TITLE
export of children in report writer

### ISSUE THREAD

**Issue by NCIEVS** [NCIEVS/nci-protege5#77]
When generating a report with the LQT from the report writer tab, it only exports the data from the current concept.  The children need to be exported and they currently aren't.

**Comment by YinghuaXu2** [comment]
Fixed in [https://github.com/bdionne/nci-edit-tab/commit/c025f82624dfaca1496aaa851dafdd673923c162](https://github.com/bdionne/nci-edit-tab/commit/c025f82624dfaca1496aaa851dafdd673923c162)

**Comment by bdionne** [comment]
fixed in [nci-0.111](https://github.com/NCIEVS/nci-protege5/releases)

**Comment by rmehri** [comment]
I have retested this fix in tag 111 and found not all properties' values exported.  
Steps to reproduce:
1)	Log into the localhost 8080 as Workflow Modeler
2)	Use a class "Activity"
3)	Go to Report Writer 
4)	Configure export LQT for all these properties “Definition, Alt Definition, Full_SYN “with their table names.
5)	Do export the report write. And you’ll see the test results below:

Test Results:
Expected:
•	All children get exported
•	All Properties with their values get exported
Actual:
•	All children are exported.
•	No all Properties’ values are exported

Please see attached screen shot and the LQT report in zip file  for more details.
Thanks,
Reza

![activity_screen shot](https://cloud.githubusercontent.com/assets/8367102/21239559/57d22418-c2d5-11e6-8fe3-8be9b52319b7.png)
[lucene-LQT-export- Tag111.zip](https://github.com/NCIEVS/nci-protege5/files/655687/lucene-LQT-export-.Tag111.zip)

**Comment by bdionne** [comment]
@rmehri - this report actually looks valid. It looks to me as if you selected the qualifiers to export at the top level, rather than from the annotations edit button on the complex properties?

**Comment by rmehri** [comment]
Hi Bob, 
I have selected the qualifier under edit tab and retested this issue using tag-116, editab-0.3.1, and the same issue still exists.  No property qualifiers and value were exported.  

*Note:  in protégé -Export value properties menu, the value_set_Loaction while in GUI shows as "Value" 

Please attached screen shots and the LQT report for more details. 

[lucene-export-Report_LQT1.zip](https://github.com/NCIEVS/nci-protege5/files/704883/lucene-export-Report_LQT1.zip)

Thanks,
Reza

**Comment by bdionne** [comment]
This report looks fine to me. @rmehri , if you want to export the qualifiers for a given property, you have to select which ones from the list of annotations. From the report you include, it appears that you are selecting those properties at the top level, as properties on the class. Those won't exist on the class which is why you'll see an empty report

**Comment by rmehri** [comment]
Hi, thanks for your feedback! I have retested this issue using tag 116, edit tab-0.3.1.  Despite the fact that I was selected the properties, but there are still missing qualifiers and values for 'definition reviewer name' and 'definition review date ', and def source.  Please see attached zip file to play the video for more details.

[lucene-export-1.zip](https://github.com/NCIEVS/nci-protege5/files/712319/lucene-export-1.zip)

Thanks,
Reza

**Comment by bdionne** [comment]
@rmehri  -- you are still making the same mistake I commented on above. `Definition Reviewer Name` and `Definition Review Date` are qualifiers, annotation on the annotations. You are selecting them as top level properties for the class. They won't show up in your report.

Perhaps I can review this for you at our weekly status. I'm not sure how else to explain it

**Comment by rmehri** [comment]
Not clear which annotation on the annotations. are referring to ? Can you please send me a screen shot or point me to your document?  I am not sure if you  watched the video.

**Comment by bdionne** [comment]
I did watch the video, and the one before also. That's the way I knew you were making a mistake.

When you look at the complex property table, the columns in those tables are the `annotations on the annotations`. So for example in the `Definition` table are `Reviewer Name` and `Review Date`

We can review at the status, you can leave this ticket for now

<img width="1022" alt="screen shot 2017-01-17 at 5 18 25 pm" src="https://cloud.githubusercontent.com/assets/31741/22042394/046f913e-dcd9-11e6-9734-7eb1788dad58.png">

**Comment by rmehri** [comment]
OK, thanks

**Comment by rmehri** [comment]
Hi,
Thanks for your feedback! This fix has been retested and verified using tag-116, edit tab -0.3.1. 
Please see attached report for details. 
[lucene-export.zip](https://github.com/NCIEVS/nci-protege5/files/717757/lucene-export.zip)

Thanks,
Reza

**Comment by NCIEVS** [comment]
Reopening.  The LQT from the ReportWriter tab is no longer generating reports for children concepts.
From [EHD]:
"Export using LQT used to give the user a chance to choose which properties to export for the concept selected in the hierarchy and all of its children. Now it is only giving the data for the concept that is selected in the hierarchy. Because of performance issues, the user cannot select additional concepts to be added. However, the expected behavior was to get the data for the selected concept and its children."

**Comment by rmehri** [comment]
Hi,
I have retested and verified this fix  using latest tag 1.0082, NCI Edit Tab 0.7.0.  Please see attached zip file to retrieve snapshot and LQT report for more details. 
 
[lucene-export.zip](https://github.com/NCIEVS/nci-protege5/files/1261979/lucene-export.zip)

Thanks,
Reza
